// Race results, merged from two sources: the scraped PCS data (src/data/cycling.json,
// regenerated by scripts/scrape_pcs.py) and the hand-written ones PCS doesn't carry
// (src/data/palmares.ts). Both the homepage and /cycling read from here so they can never
// disagree about what Vedran has won.

import data from '../data/cycling.json';
import { manualResults } from '../data/palmares';

export interface RaceResult {
  date: string;
  rank: number | null;
  race: string;
  raceClass: string | null;
  country: string | null;
  distanceKm?: number | null;
  uciPoints?: number | null;
  pcsPoints?: number | null;
  location?: string;
  url: string | null;
  /** Where this row came from — the UI marks manual rows so we never pass them off as scraped. */
  source: 'pcs' | 'manual';
}

/** A result the scraper found and one we typed in are "the same race" if date + name match. */
const key = (r: { date: string; race: string }) => `${r.date}|${r.race.toLowerCase().trim()}`;

/**
 * Every result, newest first. Manual entries win on a collision: if the scraper ever picks
 * up a race we'd typed in by hand, we keep ours until it's deleted from palmares.ts.
 */
export function allResults(): RaceResult[] {
  const merged = new Map<string, RaceResult>();
  for (const r of data.results) merged.set(key(r), { ...r, source: 'pcs' });
  for (const r of manualResults) merged.set(key(r), { ...r, source: 'manual' });

  return [...merged.values()].sort((a, b) => b.date.localeCompare(a.date));
}

/** Top-ten finishes, best placing first — the "career highlights" set. */
export function highlights(): (RaceResult & { rank: number })[] {
  return allResults()
    .filter((r): r is RaceResult & { rank: number } => r.rank != null && r.rank <= 10)
    .sort((a, b) => a.rank - b.rank || b.date.localeCompare(a.date));
}

/** The single result to lead with: best placing, most recent to break a tie. */
export function featuredResult(): (RaceResult & { rank: number }) | null {
  return highlights()[0] ?? null;
}

export const medalClass = (rank: number) =>
  rank === 1 ? 'gold' : rank === 2 ? 'silver' : rank === 3 ? 'bronze' : 'plain';

/** Count of national titles — used for the homepage stat tiles. */
export function nationalTitles(): number {
  return allResults().filter((r) => r.rank === 1 && r.raceClass === 'NC').length;
}

/** How many distinct seasons he has results for. */
export function seasonsRaced(): number {
  return new Set(allResults().map((r) => r.date.slice(0, 4))).size;
}
