// What the portfolio home page puts in its shop window. Change these to feature something
// else — no layout or CSS to touch.

export const home = {
  /** Repo names from src/data/projects.json, in the order they appear on the home page.
   *  Anything in projects.json but not listed here still shows on /projects. */
  featured: ['glucoread', 'rajhl-site', 'personal-site'],

  /** Display names for the card headings, keyed by repo name. The keys above and below
   *  have to stay repo names — they are how projects.json entries are found — so a nicer
   *  name goes here rather than into projects.json, where the next sync would undo it.
   *  A repo with no entry is shown under its repo name. */
  names: {
    glucoread: 'Glucoread',
    'rajhl-site': 'Producer Website',
    'personal-site': 'This website',
  } as Record<string, string>,

  /** Hand-written one-liners for the home page. projects.json is regenerated by
   *  `npm run sync:projects` and must never be edited by hand, so any wording we want to
   *  control lives here. A repo with no entry falls back to its GitHub description. */
  blurbs: {
    glucoread:
      'Glucose, insulin and meal tracking for people managing diabetes day to day. ' +
      'Django and PostgreSQL, self-hosted and still running.',
    'rajhl-site': 'A site for the music producer Luka Rajhl.',
    'personal-site': 'This site and the blog it links to — two Astro builds from a single repo.',
  } as Record<string, string>,
} as const;
