// What the portfolio home page puts in its shop window. Change these to feature something
// else — no layout or CSS to touch.

export const home = {
  /** Repo names from src/data/projects.json, in the order they appear on the home page.
   *  Anything in projects.json but not listed here still shows on /projects. */
  featured: ['glucoread', 'rajhl-site', 'personal-site'],

  /** Hand-written one-liners for the home page. projects.json is regenerated by
   *  `npm run sync:projects` and must never be edited by hand, so any wording we want to
   *  control lives here. A repo with no entry falls back to its GitHub description. */
  blurbs: {
    glucoread:
      'Glucose, insulin and meal tracking for people managing diabetes day to day. ' +
      'Django and PostgreSQL, self-hosted and still running.',
    'rajhl-site': 'A site for the music producer Luka Rajhl.',
    'personal-site': 'This site and the blog it links to — two Astro builds from a single repo.',
  } as Record<string, string>,
} as const;
