// Hand-written results that ProCyclingStats doesn't carry.
//
// src/data/cycling.json is generated by scripts/scrape_pcs.py and must never be edited by
// hand — this file is where off-PCS results go instead. src/lib/cycling.ts merges the two.
// Keep the shape identical to a scraped result so the merge stays honest.

export interface ManualResult {
  date: string;
  rank: number | null;
  race: string;
  raceClass: string | null;
  country: string | null;
  /** Where it was raced — PCS doesn't record this, so we show it ourselves. */
  location?: string;
  url: string | null;
}

export const manualResults: ManualResult[] = [
  {
    // Won on 28 Jun 2026, the day after the ITT. PCS has never listed it.
    date: '2026-06-28',
    rank: 1,
    race: 'National Championships North Macedonia MU - Road Race',
    raceClass: 'NC',
    country: 'MK',
    location: 'Rankovce',
    url: null,
  },
];
